include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    depend_on_referenced_packages: true
    directives_ordering: true
    eol_at_end_of_file: true
    implicit_call_tearoffs: true
    join_return_with_assignment: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    public_member_api_docs: false
    sort_constructors_first: true
    sort_pub_dependencies: true
    type_annotate_public_apis: true
    unnecessary_late: true
    use_build_context_synchronously: true

analyzer:
  exclude:
    - functions/**
  errors:
    invalid_annotation_target: ignore
