name: product_fix
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dart_appwrite: ^12.1.0
  collection: ^1.19.1
  dart_helper_utils: ^3.3.0
  result_type: ^1.0.0
  http: ^1.2.2
  html_unescape: ^2.0.0
  get_it: ^8.0.3

dev_dependencies:
  lints: ^5.0.0
